Implement PDF Export Generation
calebschoepp/canvasync pull request #24
Opened 2022-03-22 06:29 UTC by nayancprakash

# Implemented Features
* implements PDF generation for both owners and participants
* uses uploaded background PDF as template for generated PDF

2022-03-22 20:31 UTC, calebschoepp requested changes
Couple comments but great job!

2022-03-22 20:31 UTC, calebschoepp commented on db/schema.rb
> +    t.json 'data', default: '""{}""', null: false
IDK why this happens but we don't want this change.

2022-03-22 20:31 UTC, calebschoepp commented on db/migrate/20220310153625_create_exports.rb
> +      t.boolean :failed
This should be done in a new migration like `rails g migration add_failed_to_exports failed:boolean`.

2022-03-23 02:45 UTC, calebschoepp approved these changes
LGTM! :crown:

2022-03-23 16:30 UTC, ryankortbeek approved these changes
LGTM great job!

2022-03-23 17:19 UTC, merged